"""Central schema-version registry for BCOS derived artifacts.

Why this exists
---------------
Before this module, every JSON/JSONL artifact in the framework had its own
ad-hoc version handling — `digest_sidecar` raised on unknown versions
(hard-crashed the dashboard); `wiki_schema` warned only; `promote_resolutions`
had a SCHEMA_VERSION constant but never validated reads; `record_resolution`
didn't version at all. Five different policies for "what does this artifact's
shape mean and what happens on upgrade?".

This module is the single source of truth: every artifact gets one row in
`REGISTRY`, every consumer calls `validate_schema()` instead of rolling its
own check.

Migration policy
----------------
- `current`     — the version this build of the framework writes.
- `min_supported` — the oldest version this build can still READ.
                   Versions older than this raise on read; consumers should
                   prompt the user to run `update.py` to migrate.
- `policy`      — `"strict"` raises on unknown/unsupported,
                  `"warn"` logs and continues with best-effort parse.

Strict for runtime-critical artifacts (dispatcher sidecar, learning ladder).
Warn for advisory artifacts (wiki, lessons, inventory snapshots).

Usage
-----
    from _schema_versions import validate_schema

    data = json.loads(path.read_text())
    validate_schema("digest-sidecar", data.get("schema_version"), path=path)
    # raises SchemaVersionError on incompatibility (strict)
    # or returns a SchemaWarning instance (warn) for the caller to surface
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal


Policy = Literal["strict", "warn"]


@dataclass(frozen=True)
class ArtifactSchema:
    artifact_id: str
    current: str
    min_supported: str
    policy: Policy
    notes: str = ""


# The single registry. Add a row per derived artifact; never let a consumer
# define its own version constant outside this table.
REGISTRY: dict[str, ArtifactSchema] = {
    "digest-sidecar": ArtifactSchema(
        artifact_id="digest-sidecar",
        current="1.0.0",
        min_supported="0.1.0-provisional",
        policy="strict",
        notes="Daily-digest sidecar JSON. Read on every dashboard render.",
    ),
    "learned-rules": ArtifactSchema(
        artifact_id="learned-rules",
        current="1.0.0",
        min_supported="1.0.0",
        policy="strict",
        notes="Self-learning ladder canonical rules. Drives auto-fix decisions.",
    ),
    "learning-blocklist": ArtifactSchema(
        artifact_id="learning-blocklist",
        current="1.0.0",
        min_supported="1.0.0",
        policy="strict",
        notes="Rules the user has /learning forget'd. Never auto-applies blocked rules.",
    ),
    "resolutions": ArtifactSchema(
        artifact_id="resolutions",
        current="1.0.0",
        min_supported="1.0.0",
        policy="warn",
        notes="Append-only event log. Tolerant on read so partial corruption "
              "doesn't lock the auditor; corruption is surfaced separately "
              "via _jsonl_safe.CorruptionReport.",
    ),
    "context-index": ArtifactSchema(
        artifact_id="context-index",
        current="1",
        min_supported="1",
        policy="warn",
        notes="Cached frontmatter facets. Regenerable from disk; tolerate stale shape.",
    ),
    "wiki-schema": ArtifactSchema(
        artifact_id="wiki-schema",
        current="1",
        min_supported="1",
        policy="warn",
        notes="docs/_wiki/.schema.yml schema-version. Wiki frontmatter validation.",
    ),
    "ecosystem-state": ArtifactSchema(
        artifact_id="ecosystem-state",
        current="1.0",
        min_supported="1.0",
        policy="warn",
        notes="Framework inventory snapshot. Regenerated by refresh_ecosystem_state.",
    ),
    "lifecycle-routing": ArtifactSchema(
        artifact_id="lifecycle-routing",
        current="1.0.0",
        min_supported="1.0.0",
        policy="strict",
        notes="lifecycle-routing.yml — drives auto-routing decisions.",
    ),
}


class SchemaVersionError(Exception):
    """Raised by strict consumers when an artifact's version is unsupported."""


@dataclass(frozen=True)
class SchemaWarning:
    artifact_id: str
    found: str | None
    expected_current: str
    min_supported: str
    detail: str

    def as_finding(self) -> dict:
        return {
            "type": "schema-version-mismatch",
            "severity": "amber",
            "artifact": self.artifact_id,
            "found": self.found,
            "expected_current": self.expected_current,
            "min_supported": self.min_supported,
            "detail": self.detail,
        }


def validate_schema(
    artifact_id: str,
    found_version: str | None,
    *,
    path: Path | None = None,
) -> SchemaWarning | None:
    """Validate an artifact's schema version against the registry.

    Strict policy → raises `SchemaVersionError` on unknown / pre-min versions.
    Warn policy   → returns a `SchemaWarning` for the caller to surface
                   (or None if the version is current).

    Unknown `artifact_id` → raises `KeyError` so typos fail loudly during
    development rather than silently skipping validation.
    """
    schema = REGISTRY[artifact_id]
    if found_version is None:
        msg = (
            f"{artifact_id}: missing schema_version; expected {schema.current!r} "
            f"(min supported: {schema.min_supported!r})"
        )
        if schema.policy == "strict":
            raise SchemaVersionError(f"{path or artifact_id}: {msg}")
        return SchemaWarning(artifact_id, None, schema.current, schema.min_supported, msg)

    found_str = str(found_version)
    if found_str == schema.current:
        return None

    if _is_below_min(found_str, schema.min_supported):
        msg = (
            f"{artifact_id}: schema_version {found_str!r} is older than "
            f"min_supported {schema.min_supported!r}; run update.py to migrate"
        )
        if schema.policy == "strict":
            raise SchemaVersionError(f"{path or artifact_id}: {msg}")
        return SchemaWarning(artifact_id, found_str, schema.current, schema.min_supported, msg)

    # Older but still supported, or newer (forward-compat). Warn either way.
    direction = "older but still supported" if _lt(found_str, schema.current) else "newer than this build"
    return SchemaWarning(
        artifact_id,
        found_str,
        schema.current,
        schema.min_supported,
        f"{artifact_id}: schema_version {found_str!r} is {direction} (current {schema.current!r})",
    )


def _normalize(v: str) -> tuple[int, ...]:
    """Best-effort version-tuple. Pre-release suffixes sort below their base."""
    base = v.split("-", 1)[0]
    parts = []
    for piece in base.split("."):
        try:
            parts.append(int(piece))
        except ValueError:
            parts.append(0)
    return tuple(parts)


def _lt(a: str, b: str) -> bool:
    return _normalize(a) < _normalize(b)


def _is_below_min(found: str, min_supported: str) -> bool:
    return _lt(found, min_supported)
