#!/usr/bin/env python3
"""
CLEAR Context OS — Wiki Index Refresh

Regenerates `docs/_wiki/index.md` from the frontmatter of every wiki page.
Treats `index.md` as a derived artifact: it records what discovery found in
`docs/_wiki/pages/` and `docs/_wiki/source-summary/`, not authored truth.

This implements lesson L-INIT-20260404-009 ("Discovery scripts are the source
of truth for what exists; state files record what discovery found, not the
definition itself") for the wiki zone — the same pattern
`refresh_ecosystem_state.py` applies to `state.json`.

Classification rule:
- wiki page = .md file under docs/_wiki/pages/ or docs/_wiki/source-summary/
              that has YAML frontmatter

Generated content:
- Header `→ [[overview]] | [[log]]` (always emitted)
- Sources table sorted by page-type, then slug (stable order across runs)
- One row per page: title, page-type, cluster, status, last-reviewed
- Counts and per-page-type breakdown footer

Idempotent: running twice with no disk changes produces byte-identical output.

Usage:
    python .claude/scripts/refresh_wiki_index.py            # apply + summary
    python .claude/scripts/refresh_wiki_index.py --dry-run  # diff only
    python .claude/scripts/refresh_wiki_index.py --quiet    # silent unless changed
    python .claude/scripts/refresh_wiki_index.py --root .   # scan a different repo

References:
- docs/_bcos-framework/architecture/wiki-zone.md (D-11)
- docs/_planned/wiki-zone-integration/pre-flight-decisions.md (D-11)
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import sys
from pathlib import Path

WIKI_DIR = "docs/_wiki"
INDEX_REL = "docs/_wiki/index.md"
PAGE_DIRS = ("docs/_wiki/pages", "docs/_wiki/source-summary")

YAML_BLOCK_RE = re.compile(r"^---\s*\n(.*?)\n---", re.DOTALL)
YAML_FIELD_RE = re.compile(r'^([a-zA-Z][a-zA-Z0-9_-]*):\s*(.*)$', re.MULTILINE)


def _strip_quotes(value: str) -> str:
    v = value.strip()
    if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
        return v[1:-1]
    return v


def parse_frontmatter(path: Path) -> dict | None:
    """Read wiki page frontmatter via the consolidated `_wiki_yaml` parser.

    Historical context: this used to be a hand-rolled scalar-only regex parser.
    P4 consolidated three drifting parsers into `_wiki_yaml.py`; this call site
    now goes through that single source of truth. The signature is preserved
    so callers do not change.
    """
    import sys as _sys
    from pathlib import Path as _Path

    script_dir = _Path(__file__).resolve().parent
    if str(script_dir) not in _sys.path:
        _sys.path.insert(0, str(script_dir))
    from _wiki_yaml import parse_frontmatter as _parse_yaml  # noqa: E402

    return _parse_yaml(path)


def collect_pages(root: Path) -> list[dict]:
    """Walk the page-bearing wiki folders and collect frontmatter+slug for each."""
    pages = []
    for sub in PAGE_DIRS:
        d = root / sub
        if not d.is_dir():
            continue
        for path in sorted(d.glob("*.md")):
            slug = path.stem
            meta = parse_frontmatter(path) or {}
            rel = path.relative_to(root).as_posix()
            pages.append({
                "slug": slug,
                "rel": rel,
                "name": meta.get("name") or slug,
                "page-type": meta.get("page-type") or "—",
                "cluster": meta.get("cluster") or "—",
                "status": meta.get("status") or "—",
                "last-reviewed": meta.get("last-reviewed") or "—",
                "last-updated": meta.get("last-updated") or "—",
                "missing-frontmatter": meta == {},
            })
    return pages


def render_index(pages: list[dict], domain: str | None = None) -> str:
    """Render the index.md content from collected pages. Deterministic order."""
    today = datetime.date.today().strftime("%Y-%m-%d")
    title = f"# {domain} wiki" if domain else "# Wiki"

    lines = [
        "---",
        "type: wiki-index",
        "generated-by: refresh_wiki_index.py",
        f"generated-at: {today}",
        f"page-count: {len(pages)}",
        "---",
        "",
        "<!-- AUTO-GENERATED — DO NOT EDIT.",
        "     This file is regenerated by .claude/scripts/refresh_wiki_index.py",
        "     from the frontmatter of every page under docs/_wiki/pages/ and",
        "     docs/_wiki/source-summary/. Hand-edits will be overwritten on the",
        "     next run (daily, via job-index-health). To change something, edit",
        "     the underlying page's frontmatter and re-run the refresh. -->",
        "",
        title,
        "",
        "→ [[overview]] | [[log]]",
        "",
    ]

    if not pages:
        lines.append("_No wiki pages yet. Drop URLs in `queue.md` and run `/wiki run`,_")
        lines.append("_or write pages directly under `_wiki/pages/`._")
        lines.append("")
        return "\n".join(lines) + "\n"

    # Sources table — sorted by (page-type, slug) for stable, useful order
    lines.append("## Sources")
    lines.append("")
    lines.append("| Page | Page-Type | Cluster | Status | Last Reviewed |")
    lines.append("|------|-----------|---------|--------|---------------|")
    for p in sorted(pages, key=lambda x: (x["page-type"], x["slug"])):
        # Slug-style wikilink for intra-zone reference (D-04)
        lines.append(
            f"| [[{p['slug']}]] | {p['page-type']} | {p['cluster']} "
            f"| {p['status']} | {p['last-reviewed']} |"
        )
    lines.append("")

    # Per-page-type breakdown
    by_pt: dict[str, int] = {}
    for p in pages:
        by_pt[p["page-type"]] = by_pt.get(p["page-type"], 0) + 1
    lines.append("## Breakdown")
    lines.append("")
    lines.append("| Page-Type | Count |")
    lines.append("|-----------|-------|")
    for pt in sorted(by_pt.keys()):
        lines.append(f"| {pt} | {by_pt[pt]} |")
    lines.append(f"| **Total** | **{len(pages)}** |")
    lines.append("")

    # Surface broken pages so they're visible in PR review
    broken = [p for p in pages if p["missing-frontmatter"]]
    if broken:
        lines.append("## ⚠️  Pages missing frontmatter")
        lines.append("")
        for p in broken:
            lines.append(f"- `{p['rel']}`")
        lines.append("")
        lines.append("These pages have no YAML frontmatter. Add it (see `wiki-zone.md` Frontmatter Schema).")
        lines.append("")

    return "\n".join(lines) + "\n"


def read_domain_from_config(root: Path) -> str | None:
    """Read `domain:` from _wiki/.config.yml if present (informational only)."""
    cfg = root / "docs" / "_wiki" / ".config.yml"
    if not cfg.is_file():
        return None
    try:
        for line in cfg.read_text(encoding="utf-8").splitlines():
            m = re.match(r'^\s*domain:\s*(.+?)\s*$', line)
            if m:
                return _strip_quotes(m.group(1))
    except (OSError, UnicodeDecodeError):
        return None
    return None


def main() -> int:
    parser = argparse.ArgumentParser(description="Regenerate docs/_wiki/index.md from page frontmatter (D-11).")
    parser.add_argument("--root", default=".", help="Repo root (default: cwd)")
    parser.add_argument("--dry-run", action="store_true", help="Print rendered content; don't write")
    parser.add_argument("--quiet", action="store_true", help="Silent unless content changed")
    args = parser.parse_args()

    root = Path(args.root).resolve()
    wiki_dir = root / WIKI_DIR
    index_path = root / INDEX_REL

    if not wiki_dir.is_dir():
        if not args.quiet:
            print(f"refresh_wiki_index: no wiki zone at {wiki_dir} — nothing to do.")
        return 0

    pages = collect_pages(root)
    domain = read_domain_from_config(root)
    new_content = render_index(pages, domain=domain)

    if args.dry_run:
        sys.stdout.write(new_content)
        return 0

    # Idempotency check: don't rewrite if content unchanged
    existing = ""
    if index_path.is_file():
        try:
            existing = index_path.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            existing = ""

    if existing == new_content:
        if not args.quiet:
            print(f"refresh_wiki_index: {INDEX_REL} already up to date ({len(pages)} page(s)).")
        return 0

    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(new_content, encoding="utf-8")
    diff_kind = "created" if not existing else "updated"
    print(f"refresh_wiki_index: {INDEX_REL} {diff_kind} ({len(pages)} page(s)).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
